// ROCK PAPER SCISSORS
// -------------------
// INITIALISE SCORE VARIABLES
// GET COMPUTER CHOICE
// GET PLAYER CHOICE
// COMPARE CHOICES
// PRINT WINNER
// UPDATE SCORES
// LOOP UNTIL 3 GAMES WON BY PLAYER OR COMPUTER
// PRINT WINNER

